apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: the-advisor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: the-advisor
  template:
    metadata:
      labels:
        app: the-advisor
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "the-advisor"

        # Redis credentials
        vault.hashicorp.com/agent-inject-secret-redis-password: "kv/data/secret/redis"
        vault.hashicorp.com/agent-inject-template-redis-password: |
          {{`{{- with secret "kv/data/secret/redis" -}}`}}
          {{`{{ .Data.data.password }}`}}
          {{`{{- end }}`}}

        # Cohere credentials
        vault.hashicorp.com/agent-inject-secret-cohere-api-key: "kv/data/secret/cohere"
        vault.hashicorp.com/agent-inject-template-cohere-api-key: |
          {{`{{- with secret "kv/data/secret/cohere" -}}`}}
          {{`{{ .Data.data.api_key }}`}}
          {{`{{- end }}`}}

        # Discord Token credentials
        vault.hashicorp.com/agent-inject-secret-discord-token: "kv/data/secret/discord"
        vault.hashicorp.com/agent-inject-template-discord-token: |
          {{`{{- with secret "kv/data/secret/discord" -}}`}}
          {{`{{ .Data.data.token }}`}}
          {{`{{- end }}`}}
        
        restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    spec:
      serviceAccountName: the-advisor
      automountServiceAccountToken: true
      containers:
        - name: the-advisor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: BASH_ENV
              value: /vault/secrets/config
            - name: DISCORD_GUILD_ID
              value: "1269864144903864381"
            - name: DISCORD_COMMUNITY_MANAGER_ID
              value: "1321329155236958220"
